use anyhow::{Context, Result, bail};
use std::fs::{File, OpenOptions};
use std::path::{Path, PathBuf};
use std::process::{Child, Command, Stdio};
use std::sync::{Mutex, OnceLock};

static MANAGED_CORE: OnceLock<Mutex<Option<Child>>> = OnceLock::new();

fn managed_core() -> &'static Mutex<Option<Child>> {
    MANAGED_CORE.get_or_init(|| Mutex::new(None))
}

fn open_core_log_file() -> Option<File> {
    let log_dir = dirs::config_dir()
        .map(|d| d.join("clash-tui").join("logs"))
        .unwrap_or_else(|| PathBuf::from("logs"));
    let primary = std::fs::create_dir_all(&log_dir).ok().and_then(|_| {
        OpenOptions::new()
            .create(true)
            .append(true)
            .open(log_dir.join("mihomo-core.log"))
            .ok()
    });
    if primary.is_some() {
        return primary;
    }

    OpenOptions::new()
        .create(true)
        .append(true)
        .open(std::env::temp_dir().join("clash-tui-mihomo-core.log"))
        .ok()
}

fn core_log_stdio() -> (Stdio, Stdio) {
    let Some(stdout) = open_core_log_file() else {
        return (Stdio::null(), Stdio::null());
    };
    let stderr = stdout.try_clone().ok();
    (
        Stdio::from(stdout),
        stderr.map(Stdio::from).unwrap_or_else(Stdio::null),
    )
}

pub fn bundled_core_path() -> Result<PathBuf> {
    let exe_dir = std::env::current_exe()
        .context("resolve current executable")?
        .parent()
        .map(Path::to_path_buf)
        .context("resolve executable directory")?;
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let name = if cfg!(windows) {
        "mihomo.exe"
    } else {
        "mihomo"
    };
    let platform = if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "linux") {
        "linux"
    } else if cfg!(target_os = "windows") {
        "windows"
    } else {
        std::env::consts::OS
    };
    let arch = std::env::consts::ARCH;

    let candidates = [
        exe_dir.join(name),
        exe_dir.join("bin").join(name),
        exe_dir.join("..").join("lib").join("clash-tui").join(name),
        cwd.join("bin").join(name),
        PathBuf::from("/opt/clashtui").join(name),
        PathBuf::from("/opt/clash-tui").join(name),
        PathBuf::from("/usr/local/lib/clash-tui").join(name),
        cwd.join("third_party")
            .join("mihomo")
            .join(format!("{platform}-{arch}"))
            .join(name),
        cwd.join("third_party").join("mihomo").join(name),
    ];

    for path in candidates {
        if path.is_file() {
            return Ok(path);
        }
    }

    bail!(
        "未找到随程序打包的 mihomo core。请把 mihomo 放在 clash-tui 同目录、bin/{}，或安装到 /opt/clashtui/{}",
        name,
        name
    )
}

/// Check if core API is reachable.
pub async fn is_core_running(api_url: &str) -> bool {
    let client = match reqwest::Client::builder()
        .timeout(std::time::Duration::from_millis(200))
        .build()
    {
        Ok(client) => client,
        Err(_) => return false,
    };
    if let Ok(resp) = client
        .get(format!("{}/version", api_url.trim_end_matches('/')))
        .send()
        .await
    {
        return resp.status().is_success();
    }
    false
}

/// Start the bundled Mihomo core. Runtime core downloads are intentionally not used.
pub async fn start_core(config_path: &Path) -> Result<()> {
    ensure_config(config_path)?;

    if let Some(child) = managed_core().lock().unwrap().as_mut()
        && child.try_wait()?.is_none()
    {
        return Ok(());
    }

    let core_path = bundled_core_path()?;
    let config_dir = config_path
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    let (stdout, stderr) = core_log_stdio();

    log::info!(
        "Starting bundled Mihomo core: {} -d {} -f {}",
        core_path.display(),
        config_dir.display(),
        config_path.display()
    );

    let child = Command::new(&core_path)
        .arg("-d")
        .arg(&config_dir)
        .arg("-f")
        .arg(config_path)
        .stdin(Stdio::null())
        .stdout(stdout)
        .stderr(stderr)
        .spawn()
        .with_context(|| format!("start bundled mihomo core: {}", core_path.display()))?;

    *managed_core().lock().unwrap() = Some(child);
    Ok(())
}

pub async fn stop_core() {
    let mut child = managed_core().lock().unwrap().take();
    if let Some(mut child) = child.take() {
        log::info!("Stopping bundled Mihomo core...");
        let _ = child.kill();
        let _ = child.wait();
    }
}

/// Ensure default config exists.
pub fn ensure_config(path: &Path) -> Result<()> {
    if path.exists() {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    let default = r#"# Clash / Mihomo default config generated by clash-tui
mixed-port: 7890
external-controller: 127.0.0.1:9090
allow-lan: true
bind-address: '*'
mode: rule
log-level: info

proxy-providers: {}

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - DIRECT

rules:
  - MATCH,Proxy
"#;

    std::fs::write(path, default).context("write default config")?;
    Ok(())
}
